apiVersion: apps/v1
kind: Deployment
metadata:
  name: breverageapi-deployment
spec:
  selector:
    matchLabels:
      app: breverageapi-pod
  template:
    metadata:
      labels:
        app: breverageapi-pod
    spec:
      containers:
      - name: breverageapi-container
        image: techrohitnaik.azurecr.io/envoyapidemo-breverageapi
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
